# Generated by Django 5.0.6 on 2024-06-12 11:21

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Expenditures',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField()),
                ('description', models.TextField()),
                ('category', models.CharField(choices=[('Housing', 'Housing'), ('Utilities', 'Utilities'), ('Groceries', 'Groceries'), ('Transportation', 'Transportation'), ('Insurance', 'Insurance'), ('Healthcare', 'Healthcare'), ('Entertainment', 'Entertainment'), ('Food', 'Food'), ('Education', 'Education'), ('Savings', 'Savings'), ('Debt Repayment', 'Debt Repayment'), ('Clothing', 'Clothing'), ('Personal Care', 'Personal Care'), ('Gifts & Donations', 'Gifts & Donations'), ('Travel', 'Travel'), ('Subscriptions', 'Subscriptions'), ('Miscellaneous', 'Miscellaneous')], max_length=200)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Categories',
                'ordering': ['-date'],
            },
        ),
    ]
