# Generated by Django 5.0.6 on 2024-06-13 12:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('expenditures', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='expenditures',
            options={'ordering': ['-date'], 'verbose_name_plural': 'Expenditures'},
        ),
    ]
