# Generated by Django 5.0.6 on 2024-06-13 12:33

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Income',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('description', models.TextField()),
                ('source', models.CharField(choices=[('employment', 'Employment Income'), ('business', 'Business Income'), ('investment', 'Investment Income'), ('rental', 'Rental Income'), ('government', 'Government Payments'), ('miscellaneous', 'Miscellaneous')], max_length=200)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Income',
                'ordering': ['-date'],
            },
        ),
    ]
